---
- name: Apply configurations on Arista nodes
  hosts: all
  gather_facts: no
  tasks:
    - name: Configure `banner login`      
      arista.eos.eos_banner:
        banner: login
        text:
          WELCOME TO NETLABBUILDER.NET NETWORK INFRASTRUCTURE
          THIS SYSTEM IS RESTRICTED TO AUTHORIZED PERSONNEL ONLY
        state: present
