---
- name: Remove configurations on Arista nodes
  hosts: all
  gather_facts: no
  tasks:
    - name: Remove `banner login`      
      arista.eos.eos_banner:
        banner: login
        state: absent
