---
- name: Remove configurations on Arista nodes
  hosts: all
  gather_facts: no
  tasks:
    - name: Remove `banner login`      
      arista.eos.eos_banner:
        banner: login
        state: absent

    - name: Copy running-config startup-config when the runnning-config is changed
      arista.eos.eos_config:
        save_when: modified
